

[custom.all.llvm]
type   = "github"
url    = "https://github.com/wizard7377/LLVM.git"
commit = "latest:main"
ipkg   = "llvm.ipkg"
packagePath = true

[custom.all.ivm]
type   = "local"
path   = "."
ipkg   = "IVM.ipkg"